In [1]:
# dataframes - excel, csv
import pandas as pd
# excel 
# pip install openpyxl
# df= pd.read_excel('filename.xlsx')
cars= pd.read_csv('used_cars_data.csv')
cars.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [2]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7251 non-null   str
 9   Engine             7207 non-null   str
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 1.3 MB

In [3]:
cars.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [4]:
cars.shape

(7253, 14)

In [5]:
engine_index_null = cars[cars.loc[:,'Engine'].isnull()].index
engine_index_null

Index([ 194,  208,  733,  749, 1294, 1327, 1385, 1460, 2074, 2096, 2264, 2325,
       2335, 2530, 2542, 2623, 2668, 2737, 2780, 2842, 3272, 3404, 3520, 3522,
       3810, 4011, 4152, 4229, 4577, 4604, 4697, 4712, 4952, 5015, 5185, 5270,
       6042, 6541, 6544, 6633, 6643, 6651, 6677, 6685, 6880, 6902],
      dtype='int64')

In [6]:
cars.drop(engine_index_null, axis = 0, inplace = True)

In [7]:
cars.shape

(7207, 14)

In [8]:
cars.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                  0
Power                   0
Seats                   7
New_Price            6201
Price                1224
dtype: int64

In [9]:
seat_index_null = cars[cars.loc[:,'Seats'].isnull()].index

In [10]:
cars.loc[seat_index_null, :]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
229,229,Ford Figo Diesel,Bangalore,2015,70436,Diesel,Manual,First,0.0 kmpl,1498 CC,99 bhp,NaN,NaN,3.60
1917,1917,Honda City 1.5 EXI,Jaipur,2005,88000,Petrol,Manual,Second,13.0 kmpl,1493 CC,100 bhp,NaN,NaN,1.70
2369,2369,Maruti Estilo LXI,Chennai,2008,56000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,1.50
3800,3800,Ford Endeavour Hurricane LE,Mumbai,2012,129000,Diesel,Automatic,First,12.8 kmpl,2953 CC,null bhp,NaN,NaN,7.00
3882,3882,Maruti Estilo LXI,Kolkata,2010,40000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,2.50
5893,5893,Maruti Estilo LXI,Chennai,2008,51000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,1.75
6957,6957,Honda Jazz 2020 Petrol,Kochi,2019,11574,Petrol,Manual,First,0.0 kmpl,1199 CC,88.7 bhp,NaN,NaN,NaN

In [11]:
cars.drop(seat_index_null, axis =0, inplace = True)

In [12]:
cars.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                  0
Power                   0
Seats                   0
New_Price            6194
Price                1223
dtype: int64

In [13]:
cars.drop('New_Price', axis =1, inplace = True)

In [14]:
cars.shape

(7200, 13)

In [15]:
cars.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                  0
Power                   0
Seats                   0
Price                1223
dtype: int64

In [16]:
cars.Transmission.value_counts()

Transmission
Manual       5163
Automatic    2037
Name: count, dtype: int64

In [17]:
cars[(cars.Transmission == "Automatic")& (cars.Year == 2018)]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
92,92,Audi A6 2011-2015 35 TDI Premium,Coimbatore,2018,48367,Diesel,Automatic,First,17.68 kmpl,1968 CC,174.33 bhp,5.0,39.58
191,191,Land Rover Range Rover 2.2L Dynamic,Coimbatore,2018,36091,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,55.76
224,224,Mercedes-Benz New C-Class C 220d Avantgarde Ed...,Coimbatore,2018,29161,Diesel,Automatic,First,19.27 kmpl,2143 CC,167.62 bhp,5.0,39.41
255,255,Hyundai Tucson 2.0 e-VGT 2WD AT GLS,Kochi,2018,51346,Diesel,Automatic,First,16.38 kmpl,1995 CC,183 bhp,5.0,21.99
282,282,Audi Q7 3.0 TDI Quattro Technology,Kochi,2018,11287,Diesel,Automatic,First,12.07 kmpl,2967 CC,241.4 bhp,7.0,70.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7080,7080,Honda Jazz 1.2 V CVT i VTEC,Coimbatore,2018,36611,Petrol,Automatic,First,19.0 kmpl,1199 CC,88.7 bhp,5.0,NaN
7144,7144,Maruti Vitara Brezza ZDi AMT,Coimbatore,2018,57804,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN
7158,7158,Hyundai Creta 1.6 SX Plus Petrol Automatic,Coimbatore,2018,32746,Petrol,Automatic,First,13.0 kmpl,1591 CC,121.3 bhp,5.0,NaN
7184,7184,Hyundai Verna VTVT 1.6 AT SX Option,Mumbai,2018,18980,Petrol,Automatic,First,17.0 kmpl,1591 CC,121.3 bhp,5.0,NaN
7218,7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN